language: node_js
dist: trusty
node_js:
  - 6.14.3
  - 8.11.3
sudo: required
services:
  - docker
env:
  global:
    - NODE_ENV=test
before_script:
  - "docker run -d --name cloudant -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=pass -p 8080:5984 couchdb:latest"
  - "sleep 30"
  - "curl -s -X 'PUT' http://admin:pass@localhost:8080/_users"
  - "curl -s -X 'PUT' http://admin:pass@localhost:8080/my_sample_db"