language: node_js
dist: trusty
node_js: 6.14.3
sudo: required
services:
- docker
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - NODE_ENV=test
  - secure: VjOhXsvzJaaBfITlNueaCTJ6Ywqc9gOAg8UvjSWlo+bjOLJmVOLVgYj023h6ULP4GilawWka82S99yeYgGGNyiDO/6yFT0EFavAbG2LRl95wg/t4aAWuPhb8oFLpX1x42J3GUWl1LnhkgmkS6v9MaOEWFxD00mObFkyyeLlXB1cJ04fZsOJK404X89BUW8jlaqxxKHhNnFftPirlQCtBZVFnxrVt47GWsC0ztAFW+0PwDnFrno0TQhFbOaEG0sNK4AQ5qlRSDeWW577UmnLdq77G9CeXjvaSX2dYjIVxAJbQYlUm9jjeuQCTb45Q9i0kxdJcZe1gUg9Rf8EDhJUovuxS6vHIiMxq40OaJGx8zbcDAOH1I29hO0T7XvdYDTgDHsmC52M9aDzyhFFJvB5N2DPxWlVjzDqkPaHkRI/aIWBTgkf9G0Nw+C8T2fmnoSGTYgaq2KCKI3yVPBCjnx2SWh7nEHsxqe9GqBobNydmKKGTuQRGUqOW/ERMfV4+UOK98rpc3wVReyEuJnj9jKaHHX+iftC3tOuU7pOTy5H4Lg0+CdWS+FWuz3Kye4FwWnlLBmPrLU7WD1fOadC0zQ0zIrcJ2C8/dG+kGa0iU8On4lF3cDCUfDqszuJ1Z7VxUwF8JwtO2ocrH92rAvHYsBsH254enMZUsZAIT0slK7gGW+8=
before_script:
- docker run -d --privileged --volume cloudant:/srv --name cloudant --hostname cloudant.dev
  -p 8080:80 ibmcom/cloudant-developer:latest
- docker exec -ti cloudant cast license --silent
- docker exec cloudant cast database init -v -y -p pass
- sleep 30
- curl -s -X 'PUT' http://admin:pass@localhost:8080/my_sample_db
