#
# IBM Confidential OCO Source Materials
# Copyright IBM Corp. 2016-2017
#
# The source code for this program is not published or otherwise
# divested of its trade secrets, irrespective of what has
# been deposited with the U.S. Copyright Office.
#
apiVersion: v1
kind: Service
metadata:
  name: nodejs-cloudant-service
  labels:
    app: nodejs-cloudant
spec:
  type: NodePort
  selector:
    app: nodejs-cloudant
  ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000